### ISSUE TITLE
Drawing during animation and a few second after causes weirdness

### ISSUE THREAD

**Issue by jlucidar** [FabMo/fabmo-smoothsketch-app#4]
When you start drawing before the end of boot up animation, your drawing is being reset after 1~2 seconds.
It looks like their is also a period right after the animation end where you can't draw at all.
@wlyoung  also reported that he can't draw the first time he touch his screen, it starts drawing only at the second touch.

Happens in Chrome on Desktop and Mobile

**Comment by wlyoung** [comment]
My guess is that in the previous version that the first tap erased the animation sketch. The animation now disappears on its own...could it be that the tap to erase is still in there and keeping you from drawing the first time you try to sketch?

**Comment by jw4rd** [comment]
fixed
